### ISSUE TITLE
generating results data file in 'phonon' mode

### ISSUE THREAD

**Issue by eminamitani** [ogura-edu/HDNNP#218]
output the data file of predicted phonon band and dos in 'phonon' mode for post process

**Comment by ogura-edu** [comment]
modify 'phonon' mode as follows:

- Read POSCAR-unitcell
- Create supercell structures with displacement using phonopy/phono3py
- Calculate forces for each structures
- Output displacements and forces in the format required by phonopy/phono3py

Postprocessing using these output files is done by users themselves using phonopy / phono 3py

**Comment by ogura-edu** [comment]
In order to let this program "loosely coupled", leave only the part that predicts the force, and delete the part that depends on phonopy.

Postprocessing using the output file can be done as you like it.
