### ISSUE TITLE
最初期で最もシンプルな場合との比較

### ISSUE THREAD

**Issue by eminamitani** [ogura-edu/HDNNP#27]
最初期でわりと上手く行ってた状態が、なぜうまくいってたのか、いまの収束性が悪い原因のあぶり出し。念のため確認したいのだけど、MPIによる問題は無いの？

**Comment by ogura-edu** [comment]
使ってるMPI関数はallreduceとbcastだけで、簡単な同期処理にしか使ってないので問題はないと思います…  

想定している原因は、重みの更新の回数と平均化処理です。  
最初期は1つの構造に対して、HDNNPに含まれるNNの個数、つまり原子の個数と同じだけ重みを更新していましたが、    
behlerの論文にある式と違う処理になっていることに気づいて修正しました。  
現在は10個くらいのサブセットを作り、１つの構造あたりに原子が８個なので、  
10 x 8 = 80  
計80個の重みの勾配を計算し、その平均を使って重みを更新しています。  

単純に同じ計算コストをかけても更新回数が1/80になること、  
勾配が平均化されることで外れ値に対してフィットしにくくなること  
あたりが原因かなと

**Comment by ogura-edu** [comment]
データセットの中からランダムに学習させるために行っていた処理が原因でした。

当然並列している各ノードで好き勝手に乱数を発生させており、  
NNを初期化した時の重みの同期はしていましたが上記の乱数の同期をしておらず、  
各ノードでバラバラのデータセットを使ってLoss functionとgradientを計算していたため、  
フィッティングが全くできなくなっていました。
